# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class ChapterInput(BaseModel):
    config: typing.Optional["ReportConfig"] = None
    chapter: typing.Optional["ChapterRef"] = None
    pointers: typing.List[str]
    elements: typing.List["ReportElement"]

class ChapterRef(BaseModel):
    number: typing.Optional[int] = None
    title: typing.Optional[str] = None

class ReportConfig(BaseModel):
    discipline: typing.Optional[str] = None
    subject: typing.Optional[str] = None
    language: typing.Optional[str] = None
    figure_label: typing.Optional[str] = None
    table_label: typing.Optional[str] = None
    outline: typing.List["ChapterRef"]

class ReportElement(BaseModel):
    element_id: typing.Optional[str] = None
    kind: typing.Optional[str] = None
    caption: typing.Optional[str] = None
    placement_token: typing.Optional[str] = None
    reference_token: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
