# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (5)
# #########################################################################

class ExtractedDataType(str, Enum):
    NUMBER = "NUMBER"
    TEXT = "TEXT"
    CATEGORY = "CATEGORY"
    DATE = "DATE"

class ExtractionConfidence(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"

class PlotGrid(str, Enum):
    NONE = "NONE"
    MAJOR = "MAJOR"
    BOTH = "BOTH"

class PlotLineStyle(str, Enum):
    SOLID = "SOLID"
    DASHED = "DASHED"
    DOTTED = "DOTTED"
    DASHDOT = "DASHDOT"
    NONE = "NONE"

class PlotMarker(str, Enum):
    NONE = "NONE"
    CIRCLE = "CIRCLE"
    SQUARE = "SQUARE"
    TRIANGLE = "TRIANGLE"
    DIAMOND = "DIAMOND"
    CROSS = "CROSS"

# #########################################################################
# Generated classes (13)
# #########################################################################

class AxisLimit(BaseModel):
    min: typing.Optional[float] = None
    max: typing.Optional[float] = None

class ChapterInput(BaseModel):
    config: "ReportConfig"
    chapter: "ChapterRef"
    pointers: typing.List[str]
    elements: typing.List["ReportElement"]

class ChapterRef(BaseModel):
    number: int
    title: str

class CreateXYPlotIntentInput(BaseModel):
    request: str
    dataset: "DatasetMetadata"

class DatasetColumnMetadata(BaseModel):
    name: str
    unit: typing.Optional[str] = None
    data_type: ExtractedDataType

class DatasetMetadata(BaseModel):
    columns: typing.List["DatasetColumnMetadata"]
    assumptions: typing.List[str]

class ExtractedColumn(BaseModel):
    name: str
    unit: typing.Optional[str] = None
    data_type: ExtractedDataType
    values: typing.List[str]

class ExtractedDataset(BaseModel):
    data_start_line: int
    data_end_line: int
    columns: typing.List["ExtractedColumn"]
    confidence: ExtractionConfidence
    assumptions: typing.List[str]

class ReportConfig(BaseModel):
    discipline: str
    subject: str
    language: str
    figure_label: str
    table_label: str
    outline: typing.List["ChapterRef"]

class ReportElement(BaseModel):
    element_id: str
    kind: str
    caption: str
    placement_token: str
    reference_token: str

class ReviseXYPlotIntentInput(BaseModel):
    current_intent: "XYPlotIntent"
    feedback: str
    dataset: "DatasetMetadata"

class XYPlotIntent(BaseModel):
    x: str
    y: str
    caption: str
    options: "XYPlotOptions"

class XYPlotOptions(BaseModel):
    title: typing.Optional[str] = None
    x_label: typing.Optional[str] = None
    y_label: typing.Optional[str] = None
    x_lim: typing.Optional["AxisLimit"] = None
    y_lim: typing.Optional["AxisLimit"] = None
    grid: PlotGrid
    line_style: PlotLineStyle
    marker: PlotMarker
    color: typing.Optional[str] = None
    invert_x: bool
    invert_y: bool

# #########################################################################
# Generated type aliases (0)
# #########################################################################
