# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ChapterInput": types.ChapterInput,
    "stream_types.ChapterInput": stream_types.ChapterInput,

    "types.ChapterRef": types.ChapterRef,
    "stream_types.ChapterRef": stream_types.ChapterRef,

    "types.ReportConfig": types.ReportConfig,
    "stream_types.ReportConfig": stream_types.ReportConfig,

    "types.ReportElement": types.ReportElement,
    "stream_types.ReportElement": stream_types.ReportElement,


}